version: '3.7'
services:
  lilypond-build:
    container_name: lilypond-build
    hostname: lilypond-build
    image: lilypond-dev
    build: .

    volumes:
      - type: bind
        source: ${LILY_SRC_DIR}
        target: /root/lilypond-src
        read_only: true
      - type: bind
        source: ${LILY_BUILD_DIR}
        target: /root/lilypond-build
        consistency: delegated

    entrypoint: tail -f /dev/null
    stdin_open: false
    tty: false

    working_dir: /root/lilypond-build
