version: '3.7'
services:
  lilydev:
    container_name: lilydev
    hostname: lilydev
    image: lilypond-dev
    build:
        context: .
        target: lilypond-dev

    volumes:
      - type: bind
        source: ${LILY_SRC_DIR}
        target: /home/user/lilypond-src
        read_only: true
      - type: bind
        source: ${LILY_BUILD_DIR}
        target: /home/user/lilypond-build
        consistency: delegated

    entrypoint: tail -f /dev/null
    stdin_open: false
    tty: false

    user: user
    working_dir: /home/user/lilypond-build

  lilypond:
    container_name: lilypond
    hostname: lilypond
    image: lilypond
    build:
        context: .
        target: lilypond

    volumes:
      - type: bind
        source: ${HOST_EXTRA_FONTS_DIR:-/dev/null}
        target: /usr/share/fonts/host/extra
        read_only: true
      - type: bind
        source: ${HOST_SYSTEM_FONTS_DIR:-/dev/null}
        target: /usr/share/fonts/host/system
        read_only: true
      - type: bind
        source: ${LILY_BUILD_DIR}
        target: /home/user/lilypond-build
        read_only: true
      - type: bind
        source: ${LILY_SRC_DIR}
        target: /home/user/lilypond-src
        read_only: true
      - type: bind
        source: ${USER_BUILD_DIR}
        target: /home/user/user-build
        consistency: delegated
      - type: bind
        source: ${USER_FONTS_DIR:-/dev/null}
        target: /home/user/.local/share/fonts
        read_only: true
      - type: bind
        source: ${USER_SRC_DIR}
        target: /home/user/user-src
        read_only: true

    entrypoint: tail -f /dev/null
    stdin_open: false
    tty: false

    user: user
    working_dir: /home/user/user-build
